# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mu"
BBFILE_PATTERN_meta-mu = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mu = "6"

LAYERDEPENDS_meta-mu = "core"
LAYERSERIES_COMPAT_meta-mu = "scarthgap"
